### ISSUE TITLE
wildfly-elytron_*.xsd - Invalid location for import schema result in validation error

### ISSUE THREAD

**Issue by cristinel-grigoras** [jbosstools/jbosstools-server#776]
All the files from wildfly-elytron_*.xsd need edited for this invalid import.

Now is <xs:import namespace="urn:wildfly:credential-reference:1.0" schemaLocation="../controller/src/main/resources/schema/wildfly-credential-reference_1_0.xsd"/>

Working file look like

<xs:import namespace="urn:wildfly:credential-reference:1.0" schemaLocation="wildfly-credential-reference_1_0.xsd"/>

**Comment by robstryker** [comment]
I'm sorry, I'm not sure I fully understand the issue. If you could give me specific steps to replicate that'd be very useful. 

For now I've verified that the files exist both in the source structure and the build artifact where they are expected to exist. 

`grep for "credential":
                org.jboss.tools.as.catalog/plugin.xml:		<uri name="urn:wildfly:credential-reference:1.0" uri="platform:/plugin/org.jboss.tools.as.catalog/schema/xsd/wildfly-credential-reference_1_0.xsd"/>
                
		org.jboss.tools.as.catalog/plugin.xml:		<uri name="urn:wildfly:credential-reference:1.1" uri="platform:/plugin/org.jboss.tools.as.catalog/schema/xsd/wildfly-credential-reference_1_1.xsd"/>
		
# Make sure file exists where expected in plugin.xml
[rob@fedora plugins] (JBIDE-28814)$ ls org.jboss.tools.as.catalog/schema/xsd/wildfly-credential-reference_1_0.xsd
org.jboss.tools.as.catalog/schema/xsd/wildfly-credential-reference_1_0.xsd

# Make sure file exists where expected in plugin.xml
[rob@fedora plugins] (JBIDE-28814)$ ls org.jboss.tools.as.catalog/schema/xsd/wildfly-credential-reference_1_1.xsd
org.jboss.tools.as.catalog/schema/xsd/wildfly-credential-reference_1_1.xsd

# Make sure file exists in the build artifact where expected
[rob@fedora plugins] (JBIDE-28814)$ unzip -l  org.jboss.tools.as.catalog/target/org.jboss.tools.as.catalog-3.10.0-SNAPSHOT.jar | grep credential
     3276  11-21-2022 11:29   schema/xsd/wildfly-credential-reference_1_0.xsd
     4304  11-21-2022 11:29   schema/xsd/wildfly-credential-reference_1_1.xsd
`

**Comment by cristinel-grigoras** [comment]
Hi,

Thanks for response, and my mystake, the wildfly-elytron_1_0.xsd is correct. The first file with problems is 8.

Look inside the file wildfly-elytron_8_0.xsd. Line 31.

I have edited the standalone.xml file in eclipse and I get a validation error. Because inside wildfly-elytron_8.0.xsd is an import of ../controller/src/main/resources/schema/wildfly-credential-reference_1_0.xsd path.

**Comment by robstryker** [comment]
Hrmm... can you give me some more details here? I've tried opening a standalone.xml file from outside the workspace and I'm not seeing the validation errors to be honest.

**Comment by robstryker** [comment]
Maybe if you could tell me 
1) how did you open the file,
2) was it in the workspace already or part of a project somehow?
3) what jboss instance was the standalone.xml for?
4) what changes did you make to the standalone.xml to get the validation error?
5) can you show me the specific error and line number, perhaps via a screenshot?

**Comment by cristinel-grigoras** [comment]
I have used the file for test configuration. Is just put in the workspace. Maybe you have other xml catalog.

The easy way, a snapshot. 


![image](https://user-images.githubusercontent.com/91966353/211268356-e0b23aef-610f-43cf-8d68-807c733a5315.png)

![image](https://user-images.githubusercontent.com/91966353/211268616-7579993b-9231-4a2b-95e7-7f095ef7a9d9.png)

**Comment by robstryker** [comment]
@olkornii are you able to replicate this?  I've tried to either just do file -> open -> some standalone.xml file,  and i've also tried copying the standalone.xml file into some web project and opening it. I'm not seeing any validation or fails or anything

**Comment by robstryker** [comment]
I got something to validate... there's a ton of errors in the typical standalone.xml though. Seems tons of fields are marked integer but make use of the variable resolver and so appears as a string to the validator.

**Comment by cristinel-grigoras** [comment]
> I got something to validate... there's a ton of errors in the typical standalone.xml though. Seems tons of fields are marked integer but make use of the variable resolver and so appears as a string to the validator.

Yes, this is another error, but in my file for testing scope, port number values are fixed.

**Comment by olkornii** [comment]
@cristinel-grigoras 
I don't fully understand how can I check it. Would be great to have a steps for reproduce. Something like: 
1. File -> Create new project -> <some project name> / < type> 
2. File -> open -> select ...
3. ...

**Comment by cristinel-grigoras** [comment]
Hi, 
step by step,

1. open new workspace
2. create maven project, war application, jsf support. No other configs.
3. copy standalone-full.xml with elytron installed, like in image
![image](https://user-images.githubusercontent.com/91966353/211566849-9581e62d-b316-43c5-82ae-ef2262570efc.png)
4. After maven update project the validation is invoked and i have that error.

**Comment by cristinel-grigoras** [comment]
Sorry to tell you, is not fixed.
You have changed files who have no connection with real problem. 

Example:
 In this file /xsd/wildfly-elytron_15_1.xsd the problem is that is refer relative invalid path in that <xs:import /> instruction.You don't need to have a test to understand what is wrong there. I don't know what classpath you have in your computer but the import instruction refers to file outside of current plugin. The source project, from where the file was get, that path is correct. Here is broken.

**Comment by robstryker** [comment]
So, I'll explain what I did. 

You are right that /xsd/wildfly-elytron_15_1.xsd has an import with a relative path. What relative path is being imported? 

`<xs:import namespace="urn:wildfly:credential-reference:1.0" schemaLocation="../controller/src/main/resources/schema/wildfly-credential-reference_1_0.xsd"/>`

Now, I have two choices to fix this. I can either "fix" the wildfly-elytron_15_1.xsd file by removing the relative path or changing the relative path to one that works with our XML catalog. But, this comes with many downsides. Most importantly, my xsd files will now be out of sync with the official ones released in a runtime, and every time I update the xsd files I will need to manually handle these discrepencies. We try not to modify the xsd files we bundle to be different than the official versions. 

The other option is... to make sure wildfly-credential-reference_1_0.xsd is in a place that the eclipse XML catalog can find it. This means I duplicate the file from the  /schema/xsd/wildfly-credential-reference_1_0.xsd location into a new location that the relative path will find: /schema/controller/src/main/resources/schema/wildfly-credential-reference_1_1.xsd.

The XML catalog will now resolve wildfly-elytron_15_1.xsd, open it, and try to find its dependencies. It will see an import for "../controller/src/main/resources/schema/wildfly-credential-reference_1_0.xsd" and it will try to resolve that. Since that file NOW exists, the problem resolving it will disappear. 

I have built, installed, and tested this patch. While the standalone.xml file still has many errors (mostly regarding the variable resolution syntax not matching the expected type, ie, ${some.var:defaultVal} does not look like a boolean), the specific error regarding the invalid import location disappeared for me entirely. 

You have declared that my patch did not fix the problem. Did you build and test it? Or are you just assuming it is not fixed by looking at the patch?

**Comment by cristinel-grigoras** [comment]
Thanks for the detailed answer and for your work. I forgot to update the catalog.
Yes is a pain to maintain source files unchanged, but is still confusing to have files in both places. I have done a build and at the same time looked at the patch.

**Comment by robstryker** [comment]
Both options had drawbacks but managing these schema is hard enough without modifying them. Our catalog already has some duplicates for legacy purposes and so adding further duplicates to ensure the catalog functions properly was preferable to changing any schema at all.  Thanks for reporting.
